[package]
name = "custom_paintable"
version = "0.1.0"
authors = ["Vitaliy Oganesyan"]
edition = "2021"

[dependencies]
gtk = { version = "0.4", package = "gtk4" }
opencv = { version = "0.63", default-features = false, features = ["imgproc", "videoio"]}
once_cell = "1.11.0"



