[package]
name = "face_detector"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.4", package = "gtk4" }
opencv = { version = "0.63", default-features = false, features = ["imgproc", "videoio"]}

