[package]
name = "game_of_life"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
iced = { version = "0.3.0", features = ["canvas", "tokio", "debug"] }
tokio = { version = "1.0", features = ["sync"] }
itertools = "0.9"
rustc-hash = "1.1"
